記憶作成画面UI作成
Kazumasa1/memo-re pull request #11
Opened 2022-12-06 01:38 UTC by Yuuma-ujimoto

API関係は未着手
サワのコード読み解けたら実装します

2022-12-06 13:54 UTC, KleinChiu commented
`useBackend`の参考元
https://vuejs.org/guide/reusability/composables.html#async-state-example

2022-12-13 01:20 UTC, KleinChiu commented on app/plugin/router.ts
> +            path: "/b/a",
パスはあってますか？開発中パス？

2022-12-13 01:21 UTC, KleinChiu commented on app/plugin/router.ts
> +
空行

2022-12-13 01:21 UTC, KleinChiu commented on app/plugin/router.ts
> +            component: import("../views/brain/createView.vue"),
`views/brain/createView.vue`のパスが重複になっている

2022-12-13 01:25 UTC, KleinChiu reviewed
修正お願いします

2022-12-13 03:32 UTC, Yuuma-ujimoto commented
修正済み

2022-12-13 03:40 UTC, KleinChiu requested changes

2022-12-13 03:40 UTC, KleinChiu commented on app/plugin/router.ts
> +            path: "/brains/status",
`/brain/:id`ではなかった？

2022-12-13 03:52 UTC, KleinChiu reviewed
@Yuuma-ujimoto ほかのファイルが混じっている
コミットの際は気をつけてください

2022-12-13 03:52 UTC, KleinChiu approved these changes
LGTM

2022-12-13 04:05 UTC, merged