listView.viewのcssを作成
Kazumasa1/memo-re pull request #67
Opened 2022-12-26 13:50 UTC by honjii

構成が間違っていないか確認お願いします！

2022-12-26 14:40 UTC, Yuuma-ujimoto approved these changes
LGTM

2022-12-26 14:41 UTC, Yuuma-ujimoto approved these changes
LGTM2

2022-12-26 14:44 UTC, KleinChiu requested changes
image001 はコミットされてないのでビルドテストが失敗している
コメントアウトするか、何かを差し込むか、画像をコミットしてください

2022-12-26 14:47 UTC, KleinChiu commented
`.DS_STORE` はソースコードではありません
削除することをおすすめします

`.gitignore`にも入っていませんので、よろしければ追加して欲しい

2022-12-26 15:50 UTC, Yuuma-ujimoto approved these changes
OK！
@KleinChiu DS_Storeに関しては俺側で消しときます

2022-12-26 19:14 UTC, KleinChiu approved these changes
LGTM

2022-12-27 13:27 UTC, Kazumasa1 approved these changes
一旦devlopに乗っけちゃいます。

2022-12-27 13:27 UTC, merged